version: '3.8'

services:
  universodomedo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-app
    ports:
      - "80:5173"
    volumes:
      - .:/app
    command: npm run dev
    environment:
      - NODE_ENV=development
