export type ValorRitualPericia = {
    idElemento: number;
    circulosNivel: {
        idCirculoNivel: number;
        pericias: {
            idPericia: number;
            valorPE: number;
            valorBonus: number;
        }[];
    }[];
};

export const valoresRituaisPericias: ValorRitualPericia[] = [
    {
        idElemento: 1,
        circulosNivel: [
            {
                idCirculoNivel: 1,
                pericias: [
                    { idPericia: 1, valorPE: 2, valorBonus: 2 },
                    { idPericia: 2, valorPE: 2, valorBonus: 2 },
                    { idPericia: 3, valorPE: 2, valorBonus: 2 },
                    { idPericia: 4, valorPE: 2, valorBonus: 2 },
                    { idPericia: 5, valorPE: 2, valorBonus: 2 },
                    { idPericia: 6, valorPE: 2, valorBonus: 2 },
                    { idPericia: 7, valorPE: 2, valorBonus: 2 },
                    { idPericia: 8, valorPE: 2, valorBonus: 2 },
                    { idPericia: 9, valorPE: 2, valorBonus: 2 },
                    { idPericia: 10, valorPE: 2, valorBonus: 2 },
                    { idPericia: 11, valorPE: 2, valorBonus: 2 },
                    { idPericia: 12, valorPE: 2, valorBonus: 2 },
                    { idPericia: 13, valorPE: 2, valorBonus: 2 },
                    { idPericia: 14, valorPE: 2, valorBonus: 2 },
                    { idPericia: 15, valorPE: 2, valorBonus: 2 },
                    { idPericia: 16, valorPE: 2, valorBonus: 2 },
                    { idPericia: 17, valorPE: 2, valorBonus: 2 },
                    { idPericia: 18, valorPE: 2, valorBonus: 2 },
                    { idPericia: 19, valorPE: 2, valorBonus: 2 },
                    { idPericia: 20, valorPE: 2, valorBonus: 2 },
                    { idPericia: 21, valorPE: 2, valorBonus: 2 },
                    { idPericia: 22, valorPE: 2, valorBonus: 2 },
                    { idPericia: 23, valorPE: 2, valorBonus: 2 },
                    { idPericia: 24, valorPE: 2, valorBonus: 2 },
                    { idPericia: 25, valorPE: 2, valorBonus: 2 },
                    { idPericia: 26, valorPE: 2, valorBonus: 2 },
                ],
            },
            {
                idCirculoNivel: 2,
                pericias: [
                    { idPericia: 1, valorPE: 3, valorBonus: 3 },
                    { idPericia: 2, valorPE: 3, valorBonus: 3 },
                    { idPericia: 3, valorPE: 3, valorBonus: 3 },
                    { idPericia: 4, valorPE: 3, valorBonus: 3 },
                    { idPericia: 5, valorPE: 3, valorBonus: 3 },
                    { idPericia: 6, valorPE: 3, valorBonus: 3 },
                    { idPericia: 7, valorPE: 3, valorBonus: 3 },
                    { idPericia: 8, valorPE: 3, valorBonus: 3 },
                    { idPericia: 9, valorPE: 3, valorBonus: 3 },
                    { idPericia: 10, valorPE: 3, valorBonus: 3 },
                    { idPericia: 11, valorPE: 3, valorBonus: 3 },
                    { idPericia: 12, valorPE: 3, valorBonus: 3 },
                    { idPericia: 13, valorPE: 3, valorBonus: 3 },
                    { idPericia: 14, valorPE: 3, valorBonus: 3 },
                    { idPericia: 15, valorPE: 3, valorBonus: 3 },
                    { idPericia: 16, valorPE: 3, valorBonus: 3 },
                    { idPericia: 17, valorPE: 3, valorBonus: 3 },
                    { idPericia: 18, valorPE: 3, valorBonus: 3 },
                    { idPericia: 19, valorPE: 3, valorBonus: 3 },
                    { idPericia: 20, valorPE: 3, valorBonus: 3 },
                    { idPericia: 21, valorPE: 3, valorBonus: 3 },
                    { idPericia: 22, valorPE: 3, valorBonus: 3 },
                    { idPericia: 23, valorPE: 3, valorBonus: 3 },
                    { idPericia: 24, valorPE: 3, valorBonus: 3 },
                    { idPericia: 25, valorPE: 3, valorBonus: 3 },
                    { idPericia: 26, valorPE: 3, valorBonus: 3 },
                ],
            },
            {
                idCirculoNivel: 3,
                pericias: [
                    { idPericia: 1, valorPE: 5, valorBonus: 4 },
                    { idPericia: 2, valorPE: 5, valorBonus: 4 },
                    { idPericia: 3, valorPE: 5, valorBonus: 4 },
                    { idPericia: 4, valorPE: 5, valorBonus: 4 },
                    { idPericia: 5, valorPE: 5, valorBonus: 4 },
                    { idPericia: 6, valorPE: 5, valorBonus: 4 },
                    { idPericia: 7, valorPE: 5, valorBonus: 4 },
                    { idPericia: 8, valorPE: 5, valorBonus: 4 },
                    { idPericia: 9, valorPE: 5, valorBonus: 4 },
                    { idPericia: 10, valorPE: 5, valorBonus: 4 },
                    { idPericia: 11, valorPE: 5, valorBonus: 4 },
                    { idPericia: 12, valorPE: 5, valorBonus: 4 },
                    { idPericia: 13, valorPE: 5, valorBonus: 4 },
                    { idPericia: 14, valorPE: 5, valorBonus: 4 },
                    { idPericia: 15, valorPE: 5, valorBonus: 4 },
                    { idPericia: 16, valorPE: 5, valorBonus: 4 },
                    { idPericia: 17, valorPE: 5, valorBonus: 4 },
                    { idPericia: 18, valorPE: 5, valorBonus: 4 },
                    { idPericia: 19, valorPE: 5, valorBonus: 4 },
                    { idPericia: 20, valorPE: 5, valorBonus: 4 },
                    { idPericia: 21, valorPE: 5, valorBonus: 4 },
                    { idPericia: 22, valorPE: 5, valorBonus: 4 },
                    { idPericia: 23, valorPE: 5, valorBonus: 4 },
                    { idPericia: 24, valorPE: 5, valorBonus: 4 },
                    { idPericia: 25, valorPE: 5, valorBonus: 4 },
                    { idPericia: 26, valorPE: 5, valorBonus: 4 },
                ],
            },
            {
                idCirculoNivel: 4,
                pericias: [
                    { idPericia: 1, valorPE: 7, valorBonus: 5 },
                    { idPericia: 2, valorPE: 7, valorBonus: 5 },
                    { idPericia: 3, valorPE: 7, valorBonus: 5 },
                    { idPericia: 4, valorPE: 7, valorBonus: 5 },
                    { idPericia: 5, valorPE: 7, valorBonus: 5 },
                    { idPericia: 6, valorPE: 7, valorBonus: 5 },
                    { idPericia: 7, valorPE: 7, valorBonus: 4 },
                    { idPericia: 8, valorPE: 7, valorBonus: 5 },
                    { idPericia: 9, valorPE: 7, valorBonus: 5 },
                    { idPericia: 10, valorPE: 7, valorBonus: 5 },
                    { idPericia: 11, valorPE: 7, valorBonus: 5 },
                    { idPericia: 12, valorPE: 7, valorBonus: 5 },
                    { idPericia: 13, valorPE: 7, valorBonus: 5 },
                    { idPericia: 14, valorPE: 7, valorBonus: 5 },
                    { idPericia: 15, valorPE: 7, valorBonus: 5 },
                    { idPericia: 16, valorPE: 7, valorBonus: 5 },
                    { idPericia: 17, valorPE: 7, valorBonus: 5 },
                    { idPericia: 18, valorPE: 7, valorBonus: 5 },
                    { idPericia: 19, valorPE: 7, valorBonus: 5 },
                    { idPericia: 20, valorPE: 7, valorBonus: 5 },
                    { idPericia: 21, valorPE: 7, valorBonus: 5 },
                    { idPericia: 22, valorPE: 7, valorBonus: 5 },
                    { idPericia: 23, valorPE: 7, valorBonus: 5 },
                    { idPericia: 24, valorPE: 7, valorBonus: 5 },
                    { idPericia: 25, valorPE: 7, valorBonus: 5 },
                    { idPericia: 26, valorPE: 7, valorBonus: 5 },
                ],
            },
            {
                idCirculoNivel: 5,
                pericias: [
                    { idPericia: 1, valorPE: 9, valorBonus: 6 },
                    { idPericia: 2, valorPE: 9, valorBonus: 6 },
                    { idPericia: 3, valorPE: 9, valorBonus: 6 },
                    { idPericia: 4, valorPE: 9, valorBonus: 6 },
                    { idPericia: 5, valorPE: 9, valorBonus: 6 },
                    { idPericia: 6, valorPE: 9, valorBonus: 6 },
                    { idPericia: 7, valorPE: 9, valorBonus: 5 },
                    { idPericia: 8, valorPE: 9, valorBonus: 6 },
                    { idPericia: 9, valorPE: 9, valorBonus: 6 },
                    { idPericia: 10, valorPE: 9, valorBonus: 6 },
                    { idPericia: 11, valorPE: 9, valorBonus: 6 },
                    { idPericia: 12, valorPE: 9, valorBonus: 6 },
                    { idPericia: 13, valorPE: 9, valorBonus: 6 },
                    { idPericia: 14, valorPE: 9, valorBonus: 6 },
                    { idPericia: 15, valorPE: 9, valorBonus: 6 },
                    { idPericia: 16, valorPE: 9, valorBonus: 6 },
                    { idPericia: 17, valorPE: 9, valorBonus: 6 },
                    { idPericia: 18, valorPE: 9, valorBonus: 6 },
                    { idPericia: 19, valorPE: 9, valorBonus: 6 },
                    { idPericia: 20, valorPE: 9, valorBonus: 6 },
                    { idPericia: 21, valorPE: 9, valorBonus: 6 },
                    { idPericia: 22, valorPE: 9, valorBonus: 6 },
                    { idPericia: 23, valorPE: 9, valorBonus: 6 },
                    { idPericia: 24, valorPE: 9, valorBonus: 6 },
                    { idPericia: 25, valorPE: 9, valorBonus: 6 },
                    { idPericia: 26, valorPE: 9, valorBonus: 6 },
                ],
            },
            {
                idCirculoNivel: 6,
                pericias: [
                    { idPericia: 1, valorPE: 11, valorBonus: 7 },
                    { idPericia: 2, valorPE: 11, valorBonus: 7 },
                    { idPericia: 3, valorPE: 11, valorBonus: 8 },
                    { idPericia: 4, valorPE: 11, valorBonus: 7 },
                    { idPericia: 5, valorPE: 11, valorBonus: 7 },
                    { idPericia: 6, valorPE: 11, valorBonus: 8 },
                    { idPericia: 7, valorPE: 11, valorBonus: 6 },
                    { idPericia: 8, valorPE: 11, valorBonus: 8 },
                    { idPericia: 9, valorPE: 11, valorBonus: 8 },
                    { idPericia: 10, valorPE: 11, valorBonus: 8 },
                    { idPericia: 11, valorPE: 11, valorBonus: 8 },
                    { idPericia: 12, valorPE: 11, valorBonus: 8 },
                    { idPericia: 13, valorPE: 11, valorBonus: 7 },
                    { idPericia: 14, valorPE: 11, valorBonus: 8 },
                    { idPericia: 15, valorPE: 11, valorBonus: 7 },
                    { idPericia: 16, valorPE: 11, valorBonus: 8 },
                    { idPericia: 17, valorPE: 11, valorBonus: 7 },
                    { idPericia: 18, valorPE: 11, valorBonus: 8 },
                    { idPericia: 19, valorPE: 11, valorBonus: 8 },
                    { idPericia: 20, valorPE: 11, valorBonus: 8 },
                    { idPericia: 21, valorPE: 11, valorBonus: 8 },
                    { idPericia: 22, valorPE: 11, valorBonus: 8 },
                    { idPericia: 23, valorPE: 11, valorBonus: 8 },
                    { idPericia: 24, valorPE: 11, valorBonus: 8 },
                    { idPericia: 25, valorPE: 11, valorBonus: 8 },
                    { idPericia: 26, valorPE: 11, valorBonus: 8 },
                ],
            },
            {
                idCirculoNivel: 7,
                pericias: [
                    { idPericia: 1, valorPE: 13, valorBonus: 8 },
                    { idPericia: 2, valorPE: 13, valorBonus: 8 },
                    { idPericia: 3, valorPE: 13, valorBonus: 9 },
                    { idPericia: 4, valorPE: 13, valorBonus: 8 },
                    { idPericia: 5, valorPE: 13, valorBonus: 8 },
                    { idPericia: 6, valorPE: 13, valorBonus: 9 },
                    { idPericia: 7, valorPE: 13, valorBonus: 6 },
                    { idPericia: 8, valorPE: 13, valorBonus: 9 },
                    { idPericia: 9, valorPE: 13, valorBonus: 9 },
                    { idPericia: 10, valorPE: 13, valorBonus: 9 },
                    { idPericia: 11, valorPE: 13, valorBonus: 9 },
                    { idPericia: 12, valorPE: 13, valorBonus: 9 },
                    { idPericia: 13, valorPE: 13, valorBonus: 8 },
                    { idPericia: 14, valorPE: 13, valorBonus: 9 },
                    { idPericia: 15, valorPE: 13, valorBonus: 8 },
                    { idPericia: 16, valorPE: 13, valorBonus: 9 },
                    { idPericia: 17, valorPE: 13, valorBonus: 8 },
                    { idPericia: 18, valorPE: 13, valorBonus: 9 },
                    { idPericia: 19, valorPE: 13, valorBonus: 9 },
                    { idPericia: 20, valorPE: 13, valorBonus: 9 },
                    { idPericia: 21, valorPE: 13, valorBonus: 9 },
                    { idPericia: 22, valorPE: 13, valorBonus: 9 },
                    { idPericia: 23, valorPE: 13, valorBonus: 9 },
                    { idPericia: 24, valorPE: 13, valorBonus: 9 },
                    { idPericia: 25, valorPE: 13, valorBonus: 9 },
                    { idPericia: 26, valorPE: 13, valorBonus: 9 },
                ],
            },
            {
                idCirculoNivel: 8,
                pericias: [
                    { idPericia: 1, valorPE: 14, valorBonus: 8 },
                    { idPericia: 2, valorPE: 14, valorBonus: 8 },
                    { idPericia: 3, valorPE: 14, valorBonus: 10 },
                    { idPericia: 4, valorPE: 14, valorBonus: 8 },
                    { idPericia: 5, valorPE: 14, valorBonus: 8 },
                    { idPericia: 6, valorPE: 14, valorBonus: 10 },
                    { idPericia: 7, valorPE: 14, valorBonus: 7 },
                    { idPericia: 8, valorPE: 14, valorBonus: 10 },
                    { idPericia: 9, valorPE: 14, valorBonus: 10 },
                    { idPericia: 10, valorPE: 14, valorBonus: 10 },
                    { idPericia: 11, valorPE: 14, valorBonus: 10 },
                    { idPericia: 12, valorPE: 14, valorBonus: 10 },
                    { idPericia: 13, valorPE: 14, valorBonus: 8 },
                    { idPericia: 14, valorPE: 14, valorBonus: 10 },
                    { idPericia: 15, valorPE: 14, valorBonus: 8 },
                    { idPericia: 16, valorPE: 14, valorBonus: 10 },
                    { idPericia: 17, valorPE: 14, valorBonus: 8 },
                    { idPericia: 18, valorPE: 14, valorBonus: 10 },
                    { idPericia: 19, valorPE: 14, valorBonus: 10 },
                    { idPericia: 20, valorPE: 14, valorBonus: 10 },
                    { idPericia: 21, valorPE: 14, valorBonus: 10 },
                    { idPericia: 22, valorPE: 14, valorBonus: 10 },
                    { idPericia: 23, valorPE: 14, valorBonus: 10 },
                    { idPericia: 24, valorPE: 14, valorBonus: 10 },
                    { idPericia: 25, valorPE: 14, valorBonus: 10 },
                    { idPericia: 26, valorPE: 14, valorBonus: 10 },
                ],
            },
            {
                idCirculoNivel: 9,
                pericias: [
                    { idPericia: 1, valorPE: 17, valorBonus: 9 },
                    { idPericia: 2, valorPE: 17, valorBonus: 9 },
                    { idPericia: 3, valorPE: 17, valorBonus: 12 },
                    { idPericia: 4, valorPE: 17, valorBonus: 9 },
                    { idPericia: 5, valorPE: 17, valorBonus: 9 },
                    { idPericia: 6, valorPE: 17, valorBonus: 12 },
                    { idPericia: 7, valorPE: 17, valorBonus: 8 },
                    { idPericia: 8, valorPE: 17, valorBonus: 12 },
                    { idPericia: 9, valorPE: 17, valorBonus: 12 },
                    { idPericia: 10, valorPE: 17, valorBonus: 12 },
                    { idPericia: 11, valorPE: 17, valorBonus: 12 },
                    { idPericia: 12, valorPE: 17, valorBonus: 12 },
                    { idPericia: 13, valorPE: 17, valorBonus: 9 },
                    { idPericia: 14, valorPE: 17, valorBonus: 12 },
                    { idPericia: 15, valorPE: 17, valorBonus: 9 },
                    { idPericia: 16, valorPE: 17, valorBonus: 12 },
                    { idPericia: 17, valorPE: 17, valorBonus: 9 },
                    { idPericia: 18, valorPE: 17, valorBonus: 12 },
                    { idPericia: 19, valorPE: 17, valorBonus: 12 },
                    { idPericia: 20, valorPE: 17, valorBonus: 12 },
                    { idPericia: 21, valorPE: 17, valorBonus: 12 },
                    { idPericia: 22, valorPE: 17, valorBonus: 12 },
                    { idPericia: 23, valorPE: 17, valorBonus: 12 },
                    { idPericia: 24, valorPE: 17, valorBonus: 12 },
                    { idPericia: 25, valorPE: 17, valorBonus: 12 },
                    { idPericia: 26, valorPE: 17, valorBonus: 12 },
                ],
            },
            // {
            //     idCirculoNivel: 10, Circulo 3 Especial
            //     pericias: [
            //         { idPericia: 2, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 3, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 6, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 10, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 11, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 12, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 14, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 16, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 18, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 20, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 21, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 23, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 24, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 25, valorPE: 20, valorBonus: 15 },
            //     ],
            // },
        ],
    },
    {
        idElemento: 2,
        circulosNivel: [
            {
                idCirculoNivel: 1,
                pericias: [
                    { idPericia: 1, valorPE: 2, valorBonus: 2 },
                    { idPericia: 2, valorPE: 2, valorBonus: 2 },
                    { idPericia: 3, valorPE: 2, valorBonus: 2 },
                    { idPericia: 4, valorPE: 2, valorBonus: 2 },
                    { idPericia: 5, valorPE: 2, valorBonus: 2 },
                    { idPericia: 6, valorPE: 2, valorBonus: 2 },
                    { idPericia: 7, valorPE: 2, valorBonus: 2 },
                    { idPericia: 8, valorPE: 2, valorBonus: 2 },
                    { idPericia: 9, valorPE: 2, valorBonus: 2 },
                    { idPericia: 10, valorPE: 2, valorBonus: 2 },
                    { idPericia: 11, valorPE: 2, valorBonus: 2 },
                    { idPericia: 12, valorPE: 2, valorBonus: 2 },
                    { idPericia: 13, valorPE: 2, valorBonus: 2 },
                    { idPericia: 14, valorPE: 2, valorBonus: 2 },
                    { idPericia: 15, valorPE: 2, valorBonus: 2 },
                    { idPericia: 16, valorPE: 2, valorBonus: 2 },
                    { idPericia: 17, valorPE: 2, valorBonus: 2 },
                    { idPericia: 18, valorPE: 2, valorBonus: 2 },
                    { idPericia: 19, valorPE: 2, valorBonus: 2 },
                    { idPericia: 20, valorPE: 2, valorBonus: 2 },
                    { idPericia: 21, valorPE: 2, valorBonus: 2 },
                    { idPericia: 22, valorPE: 2, valorBonus: 2 },
                    { idPericia: 23, valorPE: 2, valorBonus: 2 },
                    { idPericia: 24, valorPE: 2, valorBonus: 2 },
                    { idPericia: 25, valorPE: 2, valorBonus: 2 },
                    { idPericia: 26, valorPE: 2, valorBonus: 2 },
                ],
            },
            {
                idCirculoNivel: 2,
                pericias: [
                    { idPericia: 1, valorPE: 3, valorBonus: 3 },
                    { idPericia: 2, valorPE: 3, valorBonus: 3 },
                    { idPericia: 3, valorPE: 3, valorBonus: 3 },
                    { idPericia: 4, valorPE: 3, valorBonus: 3 },
                    { idPericia: 5, valorPE: 3, valorBonus: 3 },
                    { idPericia: 6, valorPE: 3, valorBonus: 3 },
                    { idPericia: 7, valorPE: 3, valorBonus: 3 },
                    { idPericia: 8, valorPE: 3, valorBonus: 3 },
                    { idPericia: 9, valorPE: 3, valorBonus: 3 },
                    { idPericia: 10, valorPE: 3, valorBonus: 3 },
                    { idPericia: 11, valorPE: 3, valorBonus: 3 },
                    { idPericia: 12, valorPE: 3, valorBonus: 3 },
                    { idPericia: 13, valorPE: 3, valorBonus: 3 },
                    { idPericia: 14, valorPE: 3, valorBonus: 3 },
                    { idPericia: 15, valorPE: 3, valorBonus: 3 },
                    { idPericia: 16, valorPE: 3, valorBonus: 3 },
                    { idPericia: 17, valorPE: 3, valorBonus: 3 },
                    { idPericia: 18, valorPE: 3, valorBonus: 3 },
                    { idPericia: 19, valorPE: 3, valorBonus: 3 },
                    { idPericia: 20, valorPE: 3, valorBonus: 3 },
                    { idPericia: 21, valorPE: 3, valorBonus: 3 },
                    { idPericia: 22, valorPE: 3, valorBonus: 3 },
                    { idPericia: 23, valorPE: 3, valorBonus: 3 },
                    { idPericia: 24, valorPE: 3, valorBonus: 3 },
                    { idPericia: 25, valorPE: 3, valorBonus: 3 },
                    { idPericia: 26, valorPE: 3, valorBonus: 3 },
                ],
            },
            {
                idCirculoNivel: 3,
                pericias: [
                    { idPericia: 1, valorPE: 5, valorBonus: 4 },
                    { idPericia: 2, valorPE: 5, valorBonus: 4 },
                    { idPericia: 3, valorPE: 5, valorBonus: 4 },
                    { idPericia: 4, valorPE: 5, valorBonus: 4 },
                    { idPericia: 5, valorPE: 5, valorBonus: 4 },
                    { idPericia: 6, valorPE: 5, valorBonus: 4 },
                    { idPericia: 7, valorPE: 5, valorBonus: 4 },
                    { idPericia: 8, valorPE: 5, valorBonus: 4 },
                    { idPericia: 9, valorPE: 5, valorBonus: 4 },
                    { idPericia: 10, valorPE: 5, valorBonus: 4 },
                    { idPericia: 11, valorPE: 5, valorBonus: 4 },
                    { idPericia: 12, valorPE: 5, valorBonus: 4 },
                    { idPericia: 13, valorPE: 5, valorBonus: 4 },
                    { idPericia: 14, valorPE: 5, valorBonus: 4 },
                    { idPericia: 15, valorPE: 5, valorBonus: 4 },
                    { idPericia: 16, valorPE: 5, valorBonus: 4 },
                    { idPericia: 17, valorPE: 5, valorBonus: 4 },
                    { idPericia: 18, valorPE: 5, valorBonus: 4 },
                    { idPericia: 19, valorPE: 5, valorBonus: 4 },
                    { idPericia: 20, valorPE: 5, valorBonus: 4 },
                    { idPericia: 21, valorPE: 5, valorBonus: 4 },
                    { idPericia: 22, valorPE: 5, valorBonus: 4 },
                    { idPericia: 23, valorPE: 5, valorBonus: 4 },
                    { idPericia: 24, valorPE: 5, valorBonus: 4 },
                    { idPericia: 25, valorPE: 5, valorBonus: 4 },
                    { idPericia: 26, valorPE: 5, valorBonus: 4 },
                ],
            },
            {
                idCirculoNivel: 4,
                pericias: [
                    { idPericia: 1, valorPE: 7, valorBonus: 5 },
                    { idPericia: 2, valorPE: 7, valorBonus: 5 },
                    { idPericia: 3, valorPE: 7, valorBonus: 5 },
                    { idPericia: 4, valorPE: 7, valorBonus: 5 },
                    { idPericia: 5, valorPE: 7, valorBonus: 5 },
                    { idPericia: 6, valorPE: 7, valorBonus: 5 },
                    { idPericia: 7, valorPE: 7, valorBonus: 5 },
                    { idPericia: 8, valorPE: 7, valorBonus: 5 },
                    { idPericia: 9, valorPE: 7, valorBonus: 4 },
                    { idPericia: 10, valorPE: 7, valorBonus: 5 },
                    { idPericia: 11, valorPE: 7, valorBonus: 5 },
                    { idPericia: 12, valorPE: 7, valorBonus: 5 },
                    { idPericia: 13, valorPE: 7, valorBonus: 5 },
                    { idPericia: 14, valorPE: 7, valorBonus: 5 },
                    { idPericia: 15, valorPE: 7, valorBonus: 4 },
                    { idPericia: 16, valorPE: 7, valorBonus: 4 },
                    { idPericia: 17, valorPE: 7, valorBonus: 5 },
                    { idPericia: 18, valorPE: 7, valorBonus: 5 },
                    { idPericia: 19, valorPE: 7, valorBonus: 5 },
                    { idPericia: 20, valorPE: 7, valorBonus: 5 },
                    { idPericia: 21, valorPE: 7, valorBonus: 5 },
                    { idPericia: 22, valorPE: 7, valorBonus: 5 },
                    { idPericia: 23, valorPE: 7, valorBonus: 5 },
                    { idPericia: 24, valorPE: 7, valorBonus: 5 },
                    { idPericia: 25, valorPE: 7, valorBonus: 4 },
                    { idPericia: 26, valorPE: 7, valorBonus: 4 },
                ],
            },
            {
                idCirculoNivel: 5,
                pericias: [
                    { idPericia: 1, valorPE: 9, valorBonus: 6 },
                    { idPericia: 2, valorPE: 9, valorBonus: 6 },
                    { idPericia: 3, valorPE: 9, valorBonus: 6 },
                    { idPericia: 4, valorPE: 9, valorBonus: 6 },
                    { idPericia: 5, valorPE: 9, valorBonus: 6 },
                    { idPericia: 6, valorPE: 9, valorBonus: 6 },
                    { idPericia: 7, valorPE: 9, valorBonus: 6 },
                    { idPericia: 8, valorPE: 9, valorBonus: 6 },
                    { idPericia: 9, valorPE: 9, valorBonus: 5 },
                    { idPericia: 10, valorPE: 9, valorBonus: 6 },
                    { idPericia: 11, valorPE: 9, valorBonus: 6 },
                    { idPericia: 12, valorPE: 9, valorBonus: 6 },
                    { idPericia: 13, valorPE: 9, valorBonus: 6 },
                    { idPericia: 14, valorPE: 9, valorBonus: 6 },
                    { idPericia: 15, valorPE: 9, valorBonus: 5 },
                    { idPericia: 16, valorPE: 9, valorBonus: 5 },
                    { idPericia: 17, valorPE: 9, valorBonus: 6 },
                    { idPericia: 18, valorPE: 9, valorBonus: 6 },
                    { idPericia: 19, valorPE: 9, valorBonus: 6 },
                    { idPericia: 20, valorPE: 9, valorBonus: 6 },
                    { idPericia: 21, valorPE: 9, valorBonus: 6 },
                    { idPericia: 22, valorPE: 9, valorBonus: 6 },
                    { idPericia: 23, valorPE: 9, valorBonus: 6 },
                    { idPericia: 24, valorPE: 9, valorBonus: 6 },
                    { idPericia: 25, valorPE: 9, valorBonus: 5 },
                    { idPericia: 26, valorPE: 9, valorBonus: 5 },
                ],
            },
            {
                idCirculoNivel: 6,
                pericias: [
                    { idPericia: 1, valorPE: 11, valorBonus: 8 },
                    { idPericia: 2, valorPE: 11, valorBonus: 8 },
                    { idPericia: 3, valorPE: 11, valorBonus: 7 },
                    { idPericia: 4, valorPE: 11, valorBonus: 8 },
                    { idPericia: 5, valorPE: 11, valorBonus: 8 },
                    { idPericia: 6, valorPE: 11, valorBonus: 8 },
                    { idPericia: 7, valorPE: 11, valorBonus: 8 },
                    { idPericia: 8, valorPE: 11, valorBonus: 8 },
                    { idPericia: 9, valorPE: 11, valorBonus: 6 },
                    { idPericia: 10, valorPE: 11, valorBonus: 7 },
                    { idPericia: 11, valorPE: 11, valorBonus: 8 },
                    { idPericia: 12, valorPE: 11, valorBonus: 8 },
                    { idPericia: 13, valorPE: 11, valorBonus: 8 },
                    { idPericia: 14, valorPE: 11, valorBonus: 8 },
                    { idPericia: 15, valorPE: 11, valorBonus: 6 },
                    { idPericia: 16, valorPE: 11, valorBonus: 6 },
                    { idPericia: 17, valorPE: 11, valorBonus: 7 },
                    { idPericia: 18, valorPE: 11, valorBonus: 8 },
                    { idPericia: 19, valorPE: 11, valorBonus: 8 },
                    { idPericia: 20, valorPE: 11, valorBonus: 7 },
                    { idPericia: 21, valorPE: 11, valorBonus: 7 },
                    { idPericia: 22, valorPE: 11, valorBonus: 7 },
                    { idPericia: 23, valorPE: 11, valorBonus: 7 },
                    { idPericia: 24, valorPE: 11, valorBonus: 8 },
                    { idPericia: 25, valorPE: 11, valorBonus: 6 },
                    { idPericia: 26, valorPE: 11, valorBonus: 6 },
                ],
            },
            {
                idCirculoNivel: 7,
                pericias: [
                    { idPericia: 1, valorPE: 13, valorBonus: 9 },
                    { idPericia: 2, valorPE: 13, valorBonus: 9 },
                    { idPericia: 3, valorPE: 13, valorBonus: 8 },
                    { idPericia: 4, valorPE: 13, valorBonus: 9 },
                    { idPericia: 5, valorPE: 13, valorBonus: 9 },
                    { idPericia: 6, valorPE: 13, valorBonus: 9 },
                    { idPericia: 7, valorPE: 13, valorBonus: 9 },
                    { idPericia: 8, valorPE: 13, valorBonus: 9 },
                    { idPericia: 9, valorPE: 13, valorBonus: 6 },
                    { idPericia: 10, valorPE: 13, valorBonus: 8 },
                    { idPericia: 11, valorPE: 13, valorBonus: 9 },
                    { idPericia: 12, valorPE: 13, valorBonus: 9 },
                    { idPericia: 13, valorPE: 13, valorBonus: 9 },
                    { idPericia: 14, valorPE: 13, valorBonus: 9 },
                    { idPericia: 15, valorPE: 13, valorBonus: 6 },
                    { idPericia: 16, valorPE: 13, valorBonus: 6 },
                    { idPericia: 17, valorPE: 13, valorBonus: 8 },
                    { idPericia: 18, valorPE: 13, valorBonus: 9 },
                    { idPericia: 19, valorPE: 13, valorBonus: 9 },
                    { idPericia: 20, valorPE: 13, valorBonus: 8 },
                    { idPericia: 21, valorPE: 13, valorBonus: 8 },
                    { idPericia: 22, valorPE: 13, valorBonus: 8 },
                    { idPericia: 23, valorPE: 13, valorBonus: 8 },
                    { idPericia: 24, valorPE: 13, valorBonus: 9 },
                    { idPericia: 25, valorPE: 13, valorBonus: 6 },
                    { idPericia: 26, valorPE: 13, valorBonus: 6 },
                ],
            },
            {
                idCirculoNivel: 8,
                pericias: [
                    { idPericia: 1, valorPE: 14, valorBonus: 10 },
                    { idPericia: 2, valorPE: 14, valorBonus: 10 },
                    { idPericia: 3, valorPE: 14, valorBonus: 8 },
                    { idPericia: 4, valorPE: 14, valorBonus: 10 },
                    { idPericia: 5, valorPE: 14, valorBonus: 10 },
                    { idPericia: 6, valorPE: 14, valorBonus: 10 },
                    { idPericia: 7, valorPE: 14, valorBonus: 10 },
                    { idPericia: 8, valorPE: 14, valorBonus: 10 },
                    { idPericia: 9, valorPE: 14, valorBonus: 7 },
                    { idPericia: 10, valorPE: 14, valorBonus: 8 },
                    { idPericia: 11, valorPE: 14, valorBonus: 10 },
                    { idPericia: 12, valorPE: 14, valorBonus: 10 },
                    { idPericia: 13, valorPE: 14, valorBonus: 10 },
                    { idPericia: 14, valorPE: 14, valorBonus: 10 },
                    { idPericia: 15, valorPE: 14, valorBonus: 7 },
                    { idPericia: 16, valorPE: 14, valorBonus: 7 },
                    { idPericia: 17, valorPE: 14, valorBonus: 8 },
                    { idPericia: 18, valorPE: 14, valorBonus: 10 },
                    { idPericia: 19, valorPE: 14, valorBonus: 10 },
                    { idPericia: 20, valorPE: 14, valorBonus: 8 },
                    { idPericia: 21, valorPE: 14, valorBonus: 8 },
                    { idPericia: 22, valorPE: 14, valorBonus: 8 },
                    { idPericia: 23, valorPE: 14, valorBonus: 8 },
                    { idPericia: 24, valorPE: 14, valorBonus: 10 },
                    { idPericia: 25, valorPE: 14, valorBonus: 7 },
                    { idPericia: 26, valorPE: 14, valorBonus: 7 },
                ],
            },
            {
                idCirculoNivel: 9,
                pericias: [
                    { idPericia: 1, valorPE: 17, valorBonus: 12 },
                    { idPericia: 2, valorPE: 17, valorBonus: 12 },
                    { idPericia: 3, valorPE: 17, valorBonus: 9 },
                    { idPericia: 4, valorPE: 17, valorBonus: 12 },
                    { idPericia: 5, valorPE: 17, valorBonus: 12 },
                    { idPericia: 6, valorPE: 17, valorBonus: 12 },
                    { idPericia: 7, valorPE: 17, valorBonus: 12 },
                    { idPericia: 8, valorPE: 17, valorBonus: 12 },
                    { idPericia: 9, valorPE: 17, valorBonus: 8 },
                    { idPericia: 10, valorPE: 17, valorBonus: 9 },
                    { idPericia: 11, valorPE: 17, valorBonus: 12 },
                    { idPericia: 12, valorPE: 17, valorBonus: 12 },
                    { idPericia: 13, valorPE: 17, valorBonus: 12 },
                    { idPericia: 14, valorPE: 17, valorBonus: 12 },
                    { idPericia: 15, valorPE: 17, valorBonus: 8 },
                    { idPericia: 16, valorPE: 17, valorBonus: 8 },
                    { idPericia: 17, valorPE: 17, valorBonus: 9 },
                    { idPericia: 18, valorPE: 17, valorBonus: 12 },
                    { idPericia: 19, valorPE: 17, valorBonus: 12 },
                    { idPericia: 20, valorPE: 17, valorBonus: 9 },
                    { idPericia: 21, valorPE: 17, valorBonus: 9 },
                    { idPericia: 22, valorPE: 17, valorBonus: 9 },
                    { idPericia: 23, valorPE: 17, valorBonus: 9 },
                    { idPericia: 24, valorPE: 17, valorBonus: 12 },
                    { idPericia: 25, valorPE: 17, valorBonus: 8 },
                    { idPericia: 26, valorPE: 17, valorBonus: 8 },
                ],
            },
            // {
            //     idCirculoNivel: 10, Circulo 3 Especial
            //     pericias: [
            //         { idPericia: 1, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 2, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 4, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 5, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 7, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 12, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 13, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 18, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 19, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 24, valorPE: 20, valorBonus: 15 },
            //     ],
            // },
        ],
    },
    {
        idElemento: 4,
        circulosNivel: [
            {
                idCirculoNivel: 1,
                pericias: [
                    { idPericia: 1, valorPE: 2, valorBonus: 2 },
                    { idPericia: 2, valorPE: 2, valorBonus: 2 },
                    { idPericia: 3, valorPE: 2, valorBonus: 2 },
                    { idPericia: 4, valorPE: 2, valorBonus: 2 },
                    { idPericia: 5, valorPE: 2, valorBonus: 2 },
                    { idPericia: 6, valorPE: 2, valorBonus: 2 },
                    { idPericia: 7, valorPE: 2, valorBonus: 2 },
                    { idPericia: 8, valorPE: 2, valorBonus: 2 },
                    { idPericia: 9, valorPE: 2, valorBonus: 2 },
                    { idPericia: 10, valorPE: 2, valorBonus: 2 },
                    { idPericia: 11, valorPE: 2, valorBonus: 2 },
                    { idPericia: 12, valorPE: 2, valorBonus: 2 },
                    { idPericia: 13, valorPE: 2, valorBonus: 2 },
                    { idPericia: 14, valorPE: 2, valorBonus: 2 },
                    { idPericia: 15, valorPE: 2, valorBonus: 2 },
                    { idPericia: 16, valorPE: 2, valorBonus: 2 },
                    { idPericia: 17, valorPE: 2, valorBonus: 2 },
                    { idPericia: 18, valorPE: 2, valorBonus: 2 },
                    { idPericia: 19, valorPE: 2, valorBonus: 2 },
                    { idPericia: 20, valorPE: 2, valorBonus: 2 },
                    { idPericia: 21, valorPE: 2, valorBonus: 2 },
                    { idPericia: 22, valorPE: 2, valorBonus: 2 },
                    { idPericia: 23, valorPE: 2, valorBonus: 2 },
                    { idPericia: 24, valorPE: 2, valorBonus: 2 },
                    { idPericia: 25, valorPE: 2, valorBonus: 2 },
                    { idPericia: 26, valorPE: 2, valorBonus: 2 },
                ],
            },
            {
                idCirculoNivel: 2,
                pericias: [
                    { idPericia: 1, valorPE: 3, valorBonus: 3 },
                    { idPericia: 2, valorPE: 3, valorBonus: 3 },
                    { idPericia: 3, valorPE: 3, valorBonus: 3 },
                    { idPericia: 4, valorPE: 3, valorBonus: 3 },
                    { idPericia: 5, valorPE: 3, valorBonus: 3 },
                    { idPericia: 6, valorPE: 3, valorBonus: 3 },
                    { idPericia: 7, valorPE: 3, valorBonus: 3 },
                    { idPericia: 8, valorPE: 3, valorBonus: 3 },
                    { idPericia: 9, valorPE: 3, valorBonus: 3 },
                    { idPericia: 10, valorPE: 3, valorBonus: 3 },
                    { idPericia: 11, valorPE: 3, valorBonus: 3 },
                    { idPericia: 12, valorPE: 3, valorBonus: 3 },
                    { idPericia: 13, valorPE: 3, valorBonus: 3 },
                    { idPericia: 14, valorPE: 3, valorBonus: 3 },
                    { idPericia: 15, valorPE: 3, valorBonus: 3 },
                    { idPericia: 16, valorPE: 3, valorBonus: 3 },
                    { idPericia: 17, valorPE: 3, valorBonus: 3 },
                    { idPericia: 18, valorPE: 3, valorBonus: 3 },
                    { idPericia: 19, valorPE: 3, valorBonus: 3 },
                    { idPericia: 20, valorPE: 3, valorBonus: 3 },
                    { idPericia: 21, valorPE: 3, valorBonus: 3 },
                    { idPericia: 22, valorPE: 3, valorBonus: 3 },
                    { idPericia: 23, valorPE: 3, valorBonus: 3 },
                    { idPericia: 24, valorPE: 3, valorBonus: 3 },
                    { idPericia: 25, valorPE: 3, valorBonus: 3 },
                    { idPericia: 26, valorPE: 3, valorBonus: 3 },
                ],
            },
            {
                idCirculoNivel: 3,
                pericias: [
                    { idPericia: 1, valorPE: 5, valorBonus: 4 },
                    { idPericia: 2, valorPE: 5, valorBonus: 4 },
                    { idPericia: 3, valorPE: 5, valorBonus: 4 },
                    { idPericia: 4, valorPE: 5, valorBonus: 4 },
                    { idPericia: 5, valorPE: 5, valorBonus: 4 },
                    { idPericia: 6, valorPE: 5, valorBonus: 4 },
                    { idPericia: 7, valorPE: 5, valorBonus: 4 },
                    { idPericia: 8, valorPE: 5, valorBonus: 4 },
                    { idPericia: 9, valorPE: 5, valorBonus: 4 },
                    { idPericia: 10, valorPE: 5, valorBonus: 4 },
                    { idPericia: 11, valorPE: 5, valorBonus: 4 },
                    { idPericia: 12, valorPE: 5, valorBonus: 4 },
                    { idPericia: 13, valorPE: 5, valorBonus: 4 },
                    { idPericia: 14, valorPE: 5, valorBonus: 4 },
                    { idPericia: 15, valorPE: 5, valorBonus: 4 },
                    { idPericia: 16, valorPE: 5, valorBonus: 4 },
                    { idPericia: 17, valorPE: 5, valorBonus: 4 },
                    { idPericia: 18, valorPE: 5, valorBonus: 4 },
                    { idPericia: 19, valorPE: 5, valorBonus: 4 },
                    { idPericia: 20, valorPE: 5, valorBonus: 4 },
                    { idPericia: 21, valorPE: 5, valorBonus: 4 },
                    { idPericia: 22, valorPE: 5, valorBonus: 4 },
                    { idPericia: 23, valorPE: 5, valorBonus: 4 },
                    { idPericia: 24, valorPE: 5, valorBonus: 4 },
                    { idPericia: 25, valorPE: 5, valorBonus: 4 },
                    { idPericia: 26, valorPE: 5, valorBonus: 4 },
                ],
            },
            {
                idCirculoNivel: 4,
                pericias: [
                    { idPericia: 1, valorPE: 7, valorBonus: 5 },
                    { idPericia: 2, valorPE: 7, valorBonus: 4 },
                    { idPericia: 3, valorPE: 7, valorBonus: 5 },
                    { idPericia: 4, valorPE: 7, valorBonus: 4 },
                    { idPericia: 5, valorPE: 7, valorBonus: 5 },
                    { idPericia: 6, valorPE: 7, valorBonus: 5 },
                    { idPericia: 7, valorPE: 7, valorBonus: 5 },
                    { idPericia: 8, valorPE: 7, valorBonus: 5 },
                    { idPericia: 9, valorPE: 7, valorBonus: 5 },
                    { idPericia: 10, valorPE: 7, valorBonus: 5 },
                    { idPericia: 11, valorPE: 7, valorBonus: 5 },
                    { idPericia: 12, valorPE: 7, valorBonus: 5 },
                    { idPericia: 13, valorPE: 7, valorBonus: 5 },
                    { idPericia: 14, valorPE: 7, valorBonus: 5 },
                    { idPericia: 15, valorPE: 7, valorBonus: 5 },
                    { idPericia: 16, valorPE: 7, valorBonus: 5 },
                    { idPericia: 17, valorPE: 7, valorBonus: 5 },
                    { idPericia: 18, valorPE: 7, valorBonus: 5 },
                    { idPericia: 19, valorPE: 7, valorBonus: 4 },
                    { idPericia: 20, valorPE: 7, valorBonus: 5 },
                    { idPericia: 21, valorPE: 7, valorBonus: 4 },
                    { idPericia: 22, valorPE: 7, valorBonus: 5 },
                    { idPericia: 23, valorPE: 7, valorBonus: 5 },
                    { idPericia: 24, valorPE: 7, valorBonus: 5 },
                    { idPericia: 25, valorPE: 7, valorBonus: 5 },
                    { idPericia: 26, valorPE: 7, valorBonus: 5 },
                ],
            },
            {
                idCirculoNivel: 5,
                pericias: [
                    { idPericia: 1, valorPE: 9, valorBonus: 6 },
                    { idPericia: 2, valorPE: 9, valorBonus: 5 },
                    { idPericia: 3, valorPE: 9, valorBonus: 6 },
                    { idPericia: 4, valorPE: 9, valorBonus: 5 },
                    { idPericia: 5, valorPE: 9, valorBonus: 6 },
                    { idPericia: 6, valorPE: 9, valorBonus: 6 },
                    { idPericia: 7, valorPE: 9, valorBonus: 6 },
                    { idPericia: 8, valorPE: 9, valorBonus: 6 },
                    { idPericia: 9, valorPE: 9, valorBonus: 6 },
                    { idPericia: 10, valorPE: 9, valorBonus: 6 },
                    { idPericia: 11, valorPE: 9, valorBonus: 6 },
                    { idPericia: 12, valorPE: 9, valorBonus: 6 },
                    { idPericia: 13, valorPE: 9, valorBonus: 6 },
                    { idPericia: 14, valorPE: 9, valorBonus: 6 },
                    { idPericia: 15, valorPE: 9, valorBonus: 6 },
                    { idPericia: 16, valorPE: 9, valorBonus: 6 },
                    { idPericia: 17, valorPE: 9, valorBonus: 6 },
                    { idPericia: 18, valorPE: 9, valorBonus: 6 },
                    { idPericia: 19, valorPE: 9, valorBonus: 5 },
                    { idPericia: 20, valorPE: 9, valorBonus: 6 },
                    { idPericia: 21, valorPE: 9, valorBonus: 5 },
                    { idPericia: 22, valorPE: 9, valorBonus: 6 },
                    { idPericia: 23, valorPE: 9, valorBonus: 6 },
                    { idPericia: 24, valorPE: 9, valorBonus: 6 },
                    { idPericia: 25, valorPE: 9, valorBonus: 6 },
                    { idPericia: 26, valorPE: 9, valorBonus: 6 },
                ],
            },
            {
                idCirculoNivel: 6,
                pericias: [
                    { idPericia: 1, valorPE: 11, valorBonus: 7 },
                    { idPericia: 2, valorPE: 11, valorBonus: 6 },
                    { idPericia: 3, valorPE: 11, valorBonus: 7 },
                    { idPericia: 4, valorPE: 11, valorBonus: 6 },
                    { idPericia: 5, valorPE: 11, valorBonus: 7 },
                    { idPericia: 6, valorPE: 11, valorBonus: 7 },
                    { idPericia: 7, valorPE: 11, valorBonus: 8 },
                    { idPericia: 8, valorPE: 11, valorBonus: 7 },
                    { idPericia: 9, valorPE: 11, valorBonus: 7 },
                    { idPericia: 10, valorPE: 11, valorBonus: 8 },
                    { idPericia: 11, valorPE: 11, valorBonus: 8 },
                    { idPericia: 12, valorPE: 11, valorBonus: 7 },
                    { idPericia: 13, valorPE: 11, valorBonus: 8 },
                    { idPericia: 14, valorPE: 11, valorBonus: 8 },
                    { idPericia: 15, valorPE: 11, valorBonus: 8 },
                    { idPericia: 16, valorPE: 11, valorBonus: 8 },
                    { idPericia: 17, valorPE: 11, valorBonus: 8 },
                    { idPericia: 18, valorPE: 11, valorBonus: 7 },
                    { idPericia: 19, valorPE: 11, valorBonus: 6 },
                    { idPericia: 20, valorPE: 11, valorBonus: 8 },
                    { idPericia: 21, valorPE: 11, valorBonus: 6 },
                    { idPericia: 22, valorPE: 11, valorBonus: 8 },
                    { idPericia: 23, valorPE: 11, valorBonus: 7 },
                    { idPericia: 24, valorPE: 11, valorBonus: 7 },
                    { idPericia: 25, valorPE: 11, valorBonus: 8 },
                    { idPericia: 26, valorPE: 11, valorBonus: 8 },
                ],
            },
            {
                idCirculoNivel: 7,
                pericias: [
                    { idPericia: 1, valorPE: 13, valorBonus: 8 },
                    { idPericia: 2, valorPE: 13, valorBonus: 6 },
                    { idPericia: 3, valorPE: 13, valorBonus: 8 },
                    { idPericia: 4, valorPE: 13, valorBonus: 6 },
                    { idPericia: 5, valorPE: 13, valorBonus: 8 },
                    { idPericia: 6, valorPE: 13, valorBonus: 8 },
                    { idPericia: 7, valorPE: 13, valorBonus: 9 },
                    { idPericia: 8, valorPE: 13, valorBonus: 8 },
                    { idPericia: 9, valorPE: 13, valorBonus: 8 },
                    { idPericia: 10, valorPE: 13, valorBonus: 9 },
                    { idPericia: 11, valorPE: 13, valorBonus: 9 },
                    { idPericia: 12, valorPE: 13, valorBonus: 8 },
                    { idPericia: 13, valorPE: 13, valorBonus: 9 },
                    { idPericia: 14, valorPE: 13, valorBonus: 9 },
                    { idPericia: 15, valorPE: 13, valorBonus: 9 },
                    { idPericia: 16, valorPE: 13, valorBonus: 9 },
                    { idPericia: 17, valorPE: 13, valorBonus: 9 },
                    { idPericia: 18, valorPE: 13, valorBonus: 8 },
                    { idPericia: 19, valorPE: 13, valorBonus: 6 },
                    { idPericia: 20, valorPE: 13, valorBonus: 9 },
                    { idPericia: 21, valorPE: 13, valorBonus: 6 },
                    { idPericia: 22, valorPE: 13, valorBonus: 9 },
                    { idPericia: 23, valorPE: 13, valorBonus: 8 },
                    { idPericia: 24, valorPE: 13, valorBonus: 8 },
                    { idPericia: 25, valorPE: 13, valorBonus: 9 },
                    { idPericia: 26, valorPE: 13, valorBonus: 9 },
                ],
            },
            {
                idCirculoNivel: 8,
                pericias: [
                    { idPericia: 1, valorPE: 14, valorBonus: 8 },
                    { idPericia: 2, valorPE: 14, valorBonus: 7 },
                    { idPericia: 3, valorPE: 14, valorBonus: 8 },
                    { idPericia: 4, valorPE: 14, valorBonus: 7 },
                    { idPericia: 5, valorPE: 14, valorBonus: 8 },
                    { idPericia: 6, valorPE: 14, valorBonus: 8 },
                    { idPericia: 7, valorPE: 14, valorBonus: 10 },
                    { idPericia: 8, valorPE: 14, valorBonus: 8 },
                    { idPericia: 9, valorPE: 14, valorBonus: 8 },
                    { idPericia: 10, valorPE: 14, valorBonus: 10 },
                    { idPericia: 11, valorPE: 14, valorBonus: 10 },
                    { idPericia: 12, valorPE: 14, valorBonus: 8 },
                    { idPericia: 13, valorPE: 14, valorBonus: 10 },
                    { idPericia: 14, valorPE: 14, valorBonus: 10 },
                    { idPericia: 15, valorPE: 14, valorBonus: 10 },
                    { idPericia: 16, valorPE: 14, valorBonus: 10 },
                    { idPericia: 17, valorPE: 14, valorBonus: 10 },
                    { idPericia: 18, valorPE: 14, valorBonus: 8 },
                    { idPericia: 19, valorPE: 14, valorBonus: 7 },
                    { idPericia: 20, valorPE: 14, valorBonus: 10 },
                    { idPericia: 21, valorPE: 14, valorBonus: 7 },
                    { idPericia: 22, valorPE: 14, valorBonus: 10 },
                    { idPericia: 23, valorPE: 14, valorBonus: 8 },
                    { idPericia: 24, valorPE: 14, valorBonus: 8 },
                    { idPericia: 25, valorPE: 14, valorBonus: 10 },
                    { idPericia: 26, valorPE: 14, valorBonus: 10 },
                ],
            },
            {
                idCirculoNivel: 9,
                pericias: [
                    { idPericia: 1, valorPE: 17, valorBonus: 9 },
                    { idPericia: 2, valorPE: 17, valorBonus: 8 },
                    { idPericia: 3, valorPE: 17, valorBonus: 9 },
                    { idPericia: 4, valorPE: 17, valorBonus: 8 },
                    { idPericia: 5, valorPE: 17, valorBonus: 9 },
                    { idPericia: 6, valorPE: 17, valorBonus: 9 },
                    { idPericia: 7, valorPE: 17, valorBonus: 12 },
                    { idPericia: 8, valorPE: 17, valorBonus: 9 },
                    { idPericia: 9, valorPE: 17, valorBonus: 9 },
                    { idPericia: 10, valorPE: 17, valorBonus: 12 },
                    { idPericia: 11, valorPE: 17, valorBonus: 12 },
                    { idPericia: 12, valorPE: 17, valorBonus: 9 },
                    { idPericia: 13, valorPE: 17, valorBonus: 12 },
                    { idPericia: 14, valorPE: 17, valorBonus: 12 },
                    { idPericia: 15, valorPE: 17, valorBonus: 12 },
                    { idPericia: 16, valorPE: 17, valorBonus: 12 },
                    { idPericia: 17, valorPE: 17, valorBonus: 12 },
                    { idPericia: 18, valorPE: 17, valorBonus: 9 },
                    { idPericia: 19, valorPE: 17, valorBonus: 8 },
                    { idPericia: 20, valorPE: 17, valorBonus: 12 },
                    { idPericia: 21, valorPE: 17, valorBonus: 8 },
                    { idPericia: 22, valorPE: 17, valorBonus: 12 },
                    { idPericia: 23, valorPE: 17, valorBonus: 9 },
                    { idPericia: 24, valorPE: 17, valorBonus: 9 },
                    { idPericia: 25, valorPE: 17, valorBonus: 12 },
                    { idPericia: 26, valorPE: 17, valorBonus: 12 },
                ],
            },
            // {
            //     idCirculoNivel: 10, Circulo 3 Especial
            //     pericias: [
            //         { idPericia: 10, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 11, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 15, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 16, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 17, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 22, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 25, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 26, valorPE: 20, valorBonus: 15 },
            //     ],
            // },
        ],
    },
    {
        idElemento: 5,
        circulosNivel: [
            {
                idCirculoNivel: 1,
                pericias: [
                    { idPericia: 1, valorPE: 2, valorBonus: 2 },
                    { idPericia: 2, valorPE: 2, valorBonus: 2 },
                    { idPericia: 3, valorPE: 2, valorBonus: 2 },
                    { idPericia: 4, valorPE: 2, valorBonus: 2 },
                    { idPericia: 5, valorPE: 2, valorBonus: 2 },
                    { idPericia: 6, valorPE: 2, valorBonus: 2 },
                    { idPericia: 7, valorPE: 2, valorBonus: 2 },
                    { idPericia: 8, valorPE: 2, valorBonus: 2 },
                    { idPericia: 9, valorPE: 2, valorBonus: 2 },
                    { idPericia: 10, valorPE: 2, valorBonus: 2 },
                    { idPericia: 11, valorPE: 2, valorBonus: 2 },
                    { idPericia: 12, valorPE: 2, valorBonus: 2 },
                    { idPericia: 13, valorPE: 2, valorBonus: 2 },
                    { idPericia: 14, valorPE: 2, valorBonus: 2 },
                    { idPericia: 15, valorPE: 2, valorBonus: 2 },
                    { idPericia: 16, valorPE: 2, valorBonus: 2 },
                    { idPericia: 17, valorPE: 2, valorBonus: 2 },
                    { idPericia: 18, valorPE: 2, valorBonus: 2 },
                    { idPericia: 19, valorPE: 2, valorBonus: 2 },
                    { idPericia: 20, valorPE: 2, valorBonus: 2 },
                    { idPericia: 21, valorPE: 2, valorBonus: 2 },
                    { idPericia: 22, valorPE: 2, valorBonus: 2 },
                    { idPericia: 23, valorPE: 2, valorBonus: 2 },
                    { idPericia: 24, valorPE: 2, valorBonus: 2 },
                    { idPericia: 25, valorPE: 2, valorBonus: 2 },
                    { idPericia: 26, valorPE: 2, valorBonus: 2 },
                ],
            },
            {
                idCirculoNivel: 2,
                pericias: [
                    { idPericia: 1, valorPE: 3, valorBonus: 3 },
                    { idPericia: 2, valorPE: 3, valorBonus: 3 },
                    { idPericia: 3, valorPE: 3, valorBonus: 3 },
                    { idPericia: 4, valorPE: 3, valorBonus: 3 },
                    { idPericia: 5, valorPE: 3, valorBonus: 3 },
                    { idPericia: 6, valorPE: 3, valorBonus: 3 },
                    { idPericia: 7, valorPE: 3, valorBonus: 3 },
                    { idPericia: 8, valorPE: 3, valorBonus: 3 },
                    { idPericia: 9, valorPE: 3, valorBonus: 3 },
                    { idPericia: 10, valorPE: 3, valorBonus: 3 },
                    { idPericia: 11, valorPE: 3, valorBonus: 3 },
                    { idPericia: 12, valorPE: 3, valorBonus: 3 },
                    { idPericia: 13, valorPE: 3, valorBonus: 3 },
                    { idPericia: 14, valorPE: 3, valorBonus: 3 },
                    { idPericia: 15, valorPE: 3, valorBonus: 3 },
                    { idPericia: 16, valorPE: 3, valorBonus: 3 },
                    { idPericia: 17, valorPE: 3, valorBonus: 3 },
                    { idPericia: 18, valorPE: 3, valorBonus: 3 },
                    { idPericia: 19, valorPE: 3, valorBonus: 3 },
                    { idPericia: 20, valorPE: 3, valorBonus: 3 },
                    { idPericia: 21, valorPE: 3, valorBonus: 3 },
                    { idPericia: 22, valorPE: 3, valorBonus: 3 },
                    { idPericia: 23, valorPE: 3, valorBonus: 3 },
                    { idPericia: 24, valorPE: 3, valorBonus: 3 },
                    { idPericia: 25, valorPE: 3, valorBonus: 3 },
                    { idPericia: 26, valorPE: 3, valorBonus: 3 },
                ],
            },
            {
                idCirculoNivel: 3,
                pericias: [
                    { idPericia: 1, valorPE: 5, valorBonus: 4 },
                    { idPericia: 2, valorPE: 5, valorBonus: 4 },
                    { idPericia: 3, valorPE: 5, valorBonus: 4 },
                    { idPericia: 4, valorPE: 5, valorBonus: 4 },
                    { idPericia: 5, valorPE: 5, valorBonus: 4 },
                    { idPericia: 6, valorPE: 5, valorBonus: 4 },
                    { idPericia: 7, valorPE: 5, valorBonus: 4 },
                    { idPericia: 8, valorPE: 5, valorBonus: 4 },
                    { idPericia: 9, valorPE: 5, valorBonus: 4 },
                    { idPericia: 10, valorPE: 5, valorBonus: 4 },
                    { idPericia: 11, valorPE: 5, valorBonus: 4 },
                    { idPericia: 12, valorPE: 5, valorBonus: 4 },
                    { idPericia: 13, valorPE: 5, valorBonus: 4 },
                    { idPericia: 14, valorPE: 5, valorBonus: 4 },
                    { idPericia: 15, valorPE: 5, valorBonus: 4 },
                    { idPericia: 16, valorPE: 5, valorBonus: 4 },
                    { idPericia: 17, valorPE: 5, valorBonus: 4 },
                    { idPericia: 18, valorPE: 5, valorBonus: 4 },
                    { idPericia: 19, valorPE: 5, valorBonus: 4 },
                    { idPericia: 20, valorPE: 5, valorBonus: 4 },
                    { idPericia: 21, valorPE: 5, valorBonus: 4 },
                    { idPericia: 22, valorPE: 5, valorBonus: 4 },
                    { idPericia: 23, valorPE: 5, valorBonus: 4 },
                    { idPericia: 24, valorPE: 5, valorBonus: 4 },
                    { idPericia: 25, valorPE: 5, valorBonus: 4 },
                    { idPericia: 26, valorPE: 5, valorBonus: 4 },
                ],
            },
            {
                idCirculoNivel: 4,
                pericias: [
                    { idPericia: 1, valorPE: 7, valorBonus: 5 },
                    { idPericia: 2, valorPE: 7, valorBonus: 4 },
                    { idPericia: 3, valorPE: 7, valorBonus: 5 },
                    { idPericia: 4, valorPE: 7, valorBonus: 5 },
                    { idPericia: 5, valorPE: 7, valorBonus: 5 },
                    { idPericia: 6, valorPE: 7, valorBonus: 5 },
                    { idPericia: 7, valorPE: 7, valorBonus: 5 },
                    { idPericia: 8, valorPE: 7, valorBonus: 5 },
                    { idPericia: 9, valorPE: 7, valorBonus: 5 },
                    { idPericia: 10, valorPE: 7, valorBonus: 5 },
                    { idPericia: 11, valorPE: 7, valorBonus: 4 },
                    { idPericia: 12, valorPE: 7, valorBonus: 4 },
                    { idPericia: 13, valorPE: 7, valorBonus: 4 },
                    { idPericia: 14, valorPE: 7, valorBonus: 5 },
                    { idPericia: 15, valorPE: 7, valorBonus: 5 },
                    { idPericia: 16, valorPE: 7, valorBonus: 5 },
                    { idPericia: 17, valorPE: 7, valorBonus: 5 },
                    { idPericia: 18, valorPE: 7, valorBonus: 5 },
                    { idPericia: 19, valorPE: 7, valorBonus: 4 },
                    { idPericia: 20, valorPE: 7, valorBonus: 5 },
                    { idPericia: 21, valorPE: 7, valorBonus: 5 },
                    { idPericia: 22, valorPE: 7, valorBonus: 5 },
                    { idPericia: 23, valorPE: 7, valorBonus: 5 },
                    { idPericia: 24, valorPE: 7, valorBonus: 5 },
                    { idPericia: 25, valorPE: 7, valorBonus: 5 },
                    { idPericia: 26, valorPE: 7, valorBonus: 5 },
                ],
            },
            {
                idCirculoNivel: 5,
                pericias: [
                    { idPericia: 1, valorPE: 9, valorBonus: 6 },
                    { idPericia: 2, valorPE: 9, valorBonus: 5 },
                    { idPericia: 3, valorPE: 9, valorBonus: 6 },
                    { idPericia: 4, valorPE: 9, valorBonus: 6 },
                    { idPericia: 5, valorPE: 9, valorBonus: 6 },
                    { idPericia: 6, valorPE: 9, valorBonus: 6 },
                    { idPericia: 7, valorPE: 9, valorBonus: 6 },
                    { idPericia: 8, valorPE: 9, valorBonus: 6 },
                    { idPericia: 9, valorPE: 9, valorBonus: 6 },
                    { idPericia: 10, valorPE: 9, valorBonus: 6 },
                    { idPericia: 11, valorPE: 9, valorBonus: 5 },
                    { idPericia: 12, valorPE: 9, valorBonus: 5 },
                    { idPericia: 13, valorPE: 9, valorBonus: 5 },
                    { idPericia: 14, valorPE: 9, valorBonus: 6 },
                    { idPericia: 15, valorPE: 9, valorBonus: 6 },
                    { idPericia: 16, valorPE: 9, valorBonus: 6 },
                    { idPericia: 17, valorPE: 9, valorBonus: 6 },
                    { idPericia: 18, valorPE: 9, valorBonus: 6 },
                    { idPericia: 19, valorPE: 9, valorBonus: 5 },
                    { idPericia: 20, valorPE: 9, valorBonus: 6 },
                    { idPericia: 21, valorPE: 9, valorBonus: 6 },
                    { idPericia: 22, valorPE: 9, valorBonus: 6 },
                    { idPericia: 23, valorPE: 9, valorBonus: 6 },
                    { idPericia: 24, valorPE: 9, valorBonus: 6 },
                    { idPericia: 25, valorPE: 9, valorBonus: 6 },
                    { idPericia: 26, valorPE: 9, valorBonus: 6 },
                ],
            },
            {
                idCirculoNivel: 6,
                pericias: [
                    { idPericia: 1, valorPE: 11, valorBonus: 8 },
                    { idPericia: 2, valorPE: 11, valorBonus: 6 },
                    { idPericia: 3, valorPE: 11, valorBonus: 7 },
                    { idPericia: 4, valorPE: 11, valorBonus: 8 },
                    { idPericia: 5, valorPE: 11, valorBonus: 8 },
                    { idPericia: 6, valorPE: 11, valorBonus: 8 },
                    { idPericia: 7, valorPE: 11, valorBonus: 8 },
                    { idPericia: 8, valorPE: 11, valorBonus: 8 },
                    { idPericia: 9, valorPE: 11, valorBonus: 8 },
                    { idPericia: 10, valorPE: 11, valorBonus: 7 },
                    { idPericia: 11, valorPE: 11, valorBonus: 6 },
                    { idPericia: 12, valorPE: 11, valorBonus: 6 },
                    { idPericia: 13, valorPE: 11, valorBonus: 6 },
                    { idPericia: 14, valorPE: 11, valorBonus: 7 },
                    { idPericia: 15, valorPE: 11, valorBonus: 8 },
                    { idPericia: 16, valorPE: 11, valorBonus: 7 },
                    { idPericia: 17, valorPE: 11, valorBonus: 8 },
                    { idPericia: 18, valorPE: 11, valorBonus: 8 },
                    { idPericia: 19, valorPE: 11, valorBonus: 6 },
                    { idPericia: 20, valorPE: 11, valorBonus: 8 },
                    { idPericia: 21, valorPE: 11, valorBonus: 7 },
                    { idPericia: 22, valorPE: 11, valorBonus: 8 },
                    { idPericia: 23, valorPE: 11, valorBonus: 8 },
                    { idPericia: 24, valorPE: 11, valorBonus: 8 },
                    { idPericia: 25, valorPE: 11, valorBonus: 8 },
                    { idPericia: 26, valorPE: 11, valorBonus: 8 },
                ],
            },
            {
                idCirculoNivel: 7,
                pericias: [
                    { idPericia: 1, valorPE: 13, valorBonus: 9 },
                    { idPericia: 2, valorPE: 13, valorBonus: 6 },
                    { idPericia: 3, valorPE: 13, valorBonus: 8 },
                    { idPericia: 4, valorPE: 13, valorBonus: 9 },
                    { idPericia: 5, valorPE: 13, valorBonus: 9 },
                    { idPericia: 6, valorPE: 13, valorBonus: 9 },
                    { idPericia: 7, valorPE: 13, valorBonus: 9 },
                    { idPericia: 8, valorPE: 13, valorBonus: 9 },
                    { idPericia: 9, valorPE: 13, valorBonus: 9 },
                    { idPericia: 10, valorPE: 13, valorBonus: 8 },
                    { idPericia: 11, valorPE: 13, valorBonus: 6 },
                    { idPericia: 12, valorPE: 13, valorBonus: 6 },
                    { idPericia: 13, valorPE: 13, valorBonus: 6 },
                    { idPericia: 14, valorPE: 13, valorBonus: 8 },
                    { idPericia: 15, valorPE: 13, valorBonus: 9 },
                    { idPericia: 16, valorPE: 13, valorBonus: 8 },
                    { idPericia: 17, valorPE: 13, valorBonus: 9 },
                    { idPericia: 18, valorPE: 13, valorBonus: 9 },
                    { idPericia: 19, valorPE: 13, valorBonus: 6 },
                    { idPericia: 20, valorPE: 13, valorBonus: 9 },
                    { idPericia: 21, valorPE: 13, valorBonus: 8 },
                    { idPericia: 22, valorPE: 13, valorBonus: 9 },
                    { idPericia: 23, valorPE: 13, valorBonus: 9 },
                    { idPericia: 24, valorPE: 13, valorBonus: 9 },
                    { idPericia: 25, valorPE: 13, valorBonus: 9 },
                    { idPericia: 26, valorPE: 13, valorBonus: 9 },
                ],
            },
            {
                idCirculoNivel: 8,
                pericias: [
                    { idPericia: 1, valorPE: 14, valorBonus: 10 },
                    { idPericia: 2, valorPE: 14, valorBonus: 7 },
                    { idPericia: 3, valorPE: 14, valorBonus: 8 },
                    { idPericia: 4, valorPE: 14, valorBonus: 10 },
                    { idPericia: 5, valorPE: 14, valorBonus: 10 },
                    { idPericia: 6, valorPE: 14, valorBonus: 10 },
                    { idPericia: 7, valorPE: 14, valorBonus: 10 },
                    { idPericia: 8, valorPE: 14, valorBonus: 10 },
                    { idPericia: 9, valorPE: 14, valorBonus: 10 },
                    { idPericia: 10, valorPE: 14, valorBonus: 8 },
                    { idPericia: 11, valorPE: 14, valorBonus: 7 },
                    { idPericia: 12, valorPE: 14, valorBonus: 7 },
                    { idPericia: 13, valorPE: 14, valorBonus: 7 },
                    { idPericia: 14, valorPE: 14, valorBonus: 8 },
                    { idPericia: 15, valorPE: 14, valorBonus: 10 },
                    { idPericia: 16, valorPE: 14, valorBonus: 8 },
                    { idPericia: 17, valorPE: 14, valorBonus: 10 },
                    { idPericia: 18, valorPE: 14, valorBonus: 10 },
                    { idPericia: 19, valorPE: 14, valorBonus: 7 },
                    { idPericia: 20, valorPE: 14, valorBonus: 10 },
                    { idPericia: 21, valorPE: 14, valorBonus: 8 },
                    { idPericia: 22, valorPE: 14, valorBonus: 10 },
                    { idPericia: 23, valorPE: 14, valorBonus: 10 },
                    { idPericia: 24, valorPE: 14, valorBonus: 10 },
                    { idPericia: 25, valorPE: 14, valorBonus: 10 },
                    { idPericia: 26, valorPE: 14, valorBonus: 10 },
                ],
            },
            {
                idCirculoNivel: 9,
                pericias: [
                    { idPericia: 1, valorPE: 17, valorBonus: 12 },
                    { idPericia: 2, valorPE: 17, valorBonus: 8 },
                    { idPericia: 3, valorPE: 17, valorBonus: 9 },
                    { idPericia: 4, valorPE: 17, valorBonus: 12 },
                    { idPericia: 5, valorPE: 17, valorBonus: 12 },
                    { idPericia: 6, valorPE: 17, valorBonus: 12 },
                    { idPericia: 7, valorPE: 17, valorBonus: 12 },
                    { idPericia: 8, valorPE: 17, valorBonus: 12 },
                    { idPericia: 9, valorPE: 17, valorBonus: 12 },
                    { idPericia: 10, valorPE: 17, valorBonus: 9 },
                    { idPericia: 11, valorPE: 17, valorBonus: 8 },
                    { idPericia: 12, valorPE: 17, valorBonus: 8 },
                    { idPericia: 13, valorPE: 17, valorBonus: 8 },
                    { idPericia: 14, valorPE: 17, valorBonus: 9 },
                    { idPericia: 15, valorPE: 17, valorBonus: 12 },
                    { idPericia: 16, valorPE: 17, valorBonus: 9 },
                    { idPericia: 17, valorPE: 17, valorBonus: 12 },
                    { idPericia: 18, valorPE: 17, valorBonus: 12 },
                    { idPericia: 19, valorPE: 17, valorBonus: 8 },
                    { idPericia: 20, valorPE: 17, valorBonus: 12 },
                    { idPericia: 21, valorPE: 17, valorBonus: 9 },
                    { idPericia: 22, valorPE: 17, valorBonus: 12 },
                    { idPericia: 23, valorPE: 17, valorBonus: 12 },
                    { idPericia: 24, valorPE: 17, valorBonus: 12 },
                    { idPericia: 25, valorPE: 17, valorBonus: 12 },
                    { idPericia: 26, valorPE: 17, valorBonus: 12 },
                ],
            },
            // {
            //     idCirculoNivel: 10, Circulo 3 Especial
            //     pericias: [
            //         { idPericia: 4, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 5, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 6, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 7, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 8, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 9, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 15, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 20, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 23, valorPE: 20, valorBonus: 15 },
            //         { idPericia: 24, valorPE: 20, valorBonus: 15 },
            //     ],
            // },
        ],
    },
];