// tive que colocar isso para que o build não reclame de uso de cookie quando chamando endpoint. Não entendi muito bem o que muda e consequências
export const dynamic = 'force-dynamic';
export const revalidate = 0;

import './globals.css';
import styles from './styles.module.css';
import { ReactNode } from 'react';

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import Fumaca from 'Componentes/ElementosVisuais/Fumaca/Fumaca.tsx';

import { ContextoMenuSwiperEsquerdaProvider } from 'Contextos/ContextoMenuSwiperEsquerda/contexto.tsx';
import { ContextoPerformanceProvider } from 'Contextos/ContextoPerformace/contexto';
import { ContextoAutenticacaoProvider } from 'Contextos/ContextoAutenticacao/contexto';

import { Cinzel, Cinzel_Decorative, Junge } from 'next/font/google';

import MenuSwiperEsquerda from 'Componentes/Elementos/MenuSwiperEsquerda/MenuSwiperEsquerda.tsx';

import { Provider as RadixTooltip } from "@radix-ui/react-tooltip";

const cinzel = Cinzel({
  subsets: ['latin'],
  variable: '--fonte-cinzel',
}); // precisa colocar no :root

const cinzelDecorative = Cinzel_Decorative({
  subsets: ['latin'],
  weight: '700',
  variable: '--fonte-cinzel-decorative',
}); // precisa colocar no :root

const junge = Junge({
  subsets: ['latin'],
  weight: '400',
  variable: '--fonte-junge',
}); // precisa colocar no :root

export const viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-BR">
      <body>
        <ContextoPerformanceProvider>
          <ContextoAutenticacaoProvider>
            <RadixTooltip delayDuration={200} skipDelayDuration={0}>
              <ContextoMenuSwiperEsquerdaProvider>
                <ConteudoContextualizado>
                  {children}
                </ConteudoContextualizado>
              </ContextoMenuSwiperEsquerdaProvider>
            </RadixTooltip>
          </ContextoAutenticacaoProvider>
        </ContextoPerformanceProvider>
      </body>
    </html>
  );
};

function ConteudoContextualizado({ children }: { children: ReactNode }) {
  return (
    <>
      <div id={styles.aviso_orientacao}>Por favor, gire seu dispositivo para o modo paisagem</div>
      <div id={styles.recipiente_orientacao_correta}>
        <Fumaca />
        <main id={styles.main}>
          <MenuSwiperEsquerda />
          <div id={styles.recipiente_conteudo_pagina}>
            {children}
          </div>
        </main>
      </div>
    </>
  )
}

// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };