import './globals.css';
import styles from './styles.module.css';

import EmbrulhoSessionProvider from 'Embrulhos/EmbrulhoSessionProvider.tsx';
import { Providers } from 'Provedores/provedores.tsx'
import { PreloadEntities } from 'Hooks/PreloadEntities'
import Fumaca from 'Componentes/ElementosVisuais/Fumaca/Fumaca.tsx';

import Cabecalho from 'Componentes/ElementosVisuais/PaginaAterrissagem/Cabecalho/Cabecalho';

import { ContextoMenuSwiperEsquerdaProvider } from 'Contextos/ContextoMenuSwiperEsquerda/contexto.tsx';

import { Cinzel, Cinzel_Decorative, Inter } from 'next/font/google';

const cinzel = Cinzel({
  subsets: ['latin'],
  variable: '--fonte-cinzel',
});

const cinzelDecorative = Cinzel_Decorative({
  subsets: ['latin'],
  weight: '700',
  variable: '--fonte-cinzel-decorative',
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--fonte-inter',
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body>
        <EmbrulhoSessionProvider>
          <ContextoMenuSwiperEsquerdaProvider>
            <Fumaca />
            <main id={styles.main}>
              <Providers>
                <PreloadEntities />
                <div id={styles.corpo}>
                  <Cabecalho />
                  <div id={styles.recipiente_conteudo_pagina}>
                    {children}
                  </div>
                </div>
              </Providers>
            </main>
          </ContextoMenuSwiperEsquerdaProvider>
        </EmbrulhoSessionProvider>
      </body>
    </html>
  );
};

// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };