name: Deploy homog-universodomedo.com 

on:
  push:
    branches:
      - homog 

jobs:
  deploy:
    runs-on: oc2 # Use a GitHub-hosted runner
    
    env:
      NEXT_PUBLIC_BACKEND_URL: ${{ secrets.HOMOG_NEXT_PUBLIC_BACKEND_URL }}
      NEXT_PUBLIC_ENV: ${{ secrets.HOMOG_NEXT_PUBLIC_ENV  }}
      NEXT_PUBLIC_WEBSOCKET_URL: ${{ secrets.HOMOG_NEXT_PUBLIC_WEBSOCKET_URL }}
      NEXT_PUBLIC_IMAGE_API_URL: ${{ secrets.HOMOG_NEXT_PUBLIC_IMAGE_API_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: homog
        submodules: true  # Ensure submodules are updated

    - name: Prepare Docker files
      run: |
        cp -r deployment/docker/* ./

    - name: Build and deploy containers with Docker Compose
      run: docker compose -p universodomedo up --build -d --force-recreate
