name: Build and Deploy

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: udm-oc1-a
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install npm dependencies
      run: npm install

    - name: Install TypeScript globally
      run: npm install -g typescript

    - name: Install Vite globally
      run: npm install -g vite

    - name: Build the project
      run: npm run build

    - name: Copy build artifacts to Docker volume
      run: cp -r ./dist/* ~/docker/volumes/universodomedo/site
