name: Build and Deploy

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: udm-oc1-a
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the project in a Docker container
      run: | 
        docker run --name build-container --rm -v ${GITHUB_WORKSPACE}:/app -w /app node:18 bash -c "npm install && npm install -g typescript && npm install -g vite && npm run build"

    - name: Copy build artifacts to Docker volume
      run: |
        docker cp build-container:/app/dist ~/docker/volumes/universodomedo/site
